### ISSUE TITLE
cURL error 3: <url> malformed

### ISSUE THREAD

**Issue by AvengersArmy** [mgufrone/cpanel-whm#12]
Hi i am using Laravel 5.1, and performed the following steps to create an email account but i keep getting the error - cURL error 3: <url> malformed

Step 1: Add to compposer.json -> require -> "gufy/cpanel-whm":"~1.0"
Step 2: composer update
Step 3: added to routes.php
        use Gufy\CpanelPhp\Cpanel;
        Route::get('/temp', function () {
        $cpanel =  new Cpanel;
	$cpanel->addEmailAccount('test', 'test@domain.ca', 'test123!');
	echo 'Done';
        });

Could i please request some help with this?

**Comment by mgufrone** [comment]
have you already done this before

```
   php artisan vendor:publish gufy/cpanel-whm
```

and afterwards you have to change its content, i believe it will be located at config/cpanel-whm.php 
especially on the `host` key

**Comment by AvengersArmy** [comment]
Yes i have done that, i ended up using another method to do this - CpanelWhm::cpanel('Email','addpop', 'superdash', array('domain'=>'domain.com', 'email'=>'test', 'password'=>'test123','quota'=>'250'));

**Comment by lrpasquetto** [comment]
Could deploy the API 1 WHM
