### ISSUE TITLE
vendor publish not working

### ISSUE THREAD

**Issue by lionslair** [mgufrone/cpanel-whm#19]
Trying to use this with Laravel 5.4

Installed then trying to run

php artisan vendor:publish gufy/cpanel-whm

gives the error 

  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".

**Comment by poxin13** [comment]
Running into this too, what was your fix?

**Comment by lionslair** [comment]
I removed it and are not using it. I am using "gufy/cpanel-php": "dev-master", only. 

Has some helpers in it but then I am just using the cpanel/ whm api  UAPI and it works a treat.
