### ISSUE TITLE
Laravel 5.4 support?

### ISSUE THREAD

**Issue by drakakisgeo** [mgufrone/cpanel-whm#21]
I get an error like this in CpanelWhmServiceProvider.php line 32

> Call to undefined method Illuminate\Foundation\Application::share()

There where some changes in the framework, share() method was dropped.

**Comment by drakakisgeo** [comment]
The fork is working fine for me, so most probably you just need to tag a new version. I see that it's already fixed but I can't use the dev-master version.

**Comment by mgufrone** [comment]
It's bumped now. Take a look at v1.0.3. Sorry for the delay
