### ISSUE TITLE
Email syntax

### ISSUE THREAD

**Issue by rogepage** [mgufrone/cpanel-whm#3]
What is the syntax in this case?
/json-api/cpanel?cpanel_jsonapi_apiversion=2&cpanel_jsonapi_module=Email&cpanel_jsonapi_func=accountname&account="user@example.com"

**Comment by mgufrone** [comment]
the email value must be quoted? am i right?

**Comment by mgufrone** [comment]
owh sorry, i misunderstood what do you mean. I will try it first and see what happen there.

**Comment by mgufrone** [comment]
it would be like this

```
$results = CpanelWhm::cpanel([
			'cpanel_jsonapi_version'=>2,
			'cpanel_jsonapi_module'=>'Email',
			'cpanel_jsonapi_func'=>'accountname',
			'cpanel_jsonapi_user'=>'benarkah'
	])
```
i guess it's time to improve this API Call. Thanks for using this package.

**Comment by mgufrone** [comment]
If you update this package : `gufy/cpanel-php`, you can use this method
```php
<?php
$results = CpanelWhm::cpanel('Email','accountname','username',['account'=>'user@example.com']);
```

**Comment by rogepage** [comment]
Thanks for help.
I did update to Installing gufy/cpanel-php (v1.0.1)
but when I make the call
$param =  array( 'domain' => 'inbr.com.br', 'nearquotaonly'   => '0',  'no_validate'     => '0' ) ;
$results = CpanelWhm::cpanel('Email','listpopswithdisk',$param);
Exception User parameter is invalid or was not supplied

**Comment by mgufrone** [comment]
Yap, you need to provider username at the 3rd parameter. Based on cPanel API Documentation, it requires username as the parameter. Your code should be like this

```php
$param = array( 'domain' => 'inbr.com.br', 'nearquotaonly' => '0', 'no_validate' => '0' ) ;
$results = CpanelWhm::cpanel('Email','listpopswithdisk', 'username', $param);
```

**Comment by rogepage** [comment]
Perfect! Very usefull.

**Comment by mgufrone** [comment]
great. glad to hear that this package is really helpful for you. thank you for using this package. :+1:
