### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by AvengersArmy** [mgufrone/cpanel-whm#8]
Can i use this package with Laravel 5 and the new API structures as listed here - https://documentation.cpanel.net/display/SDK/Software+Development+Kit+Home ???

It seems your links to the whm+cpanel api lead to 404's...

**Comment by kayyyy** [comment]
If you take a look at the composer you will see Support for version 5.

And if you would read the readme you would read "If you are Laravel 4 user, please use v1.0.1 version instead.".

Guess what this means? Exactly, support for L5.

**Comment by mgufrone** [comment]
Yes you can, @AvengersArmy, please use the latest tag.
